// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'so_phieu_filter_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SoPhieuFilterModel _$SoPhieuFilterModelFromJson(Map<String, dynamic> json) =>
    SoPhieuFilterModel(
      sophieu: json['sophieu'] as String?,
      sophieucan: json['sophieucan'] as String?,
      idenct: json['idenct'] as num?,
      id: json['id'] as int?,
      idLocal: json['idLocal'] as int?,
      so_bbtm: json['so_bbtm'] as String?,
      mand: json['mand'] as String?,
      tennd: json['tennd'] as String?,
      ngaycanstr: json['ngaycanstr'] as String?,
      makhuruong: json['makhuruong'] as String?,
      tenkhuruong: json['tenkhuruong'] as String?,
      magiong: json['magiong'] as String?,
      tengiong: json['tengiong'] as String?,
      ngaycan: json['ngaycan'] as String?,
      huyen: json['huyen'] as String?,
      tenhuyen: json['tenhuyen'] as String?,
      tentinh: json['tentinh'] as String?,
      tenxa: json['tenxa'] as String?,
      tinh: json['tinh'] as String?,
      xa: json['xa'] as String?,
      ngaycoghe: json['ngaycoghe'] as String?,
      ngaycoghestr: json['ngaycoghestr'] as String?,
      ghichu: json['ghichu'] as String?,
      canluaList: (json['canluaList'] as List<dynamic>?)
          ?.map((e) => BagRiceEntity.fromJson(e as Map<String, dynamic>))
          .toList(),
      isNotSync: json['isNotSync'] as bool?,
      tieuchuan: json['tieuchuan'] as String?,
      dientichchot: json['dientichchot'] as num?,
      giachot: json['giachot'] as num?,
      tongkhoiluong_tru_bao: json['tongkhoiluong_tru_bao'] as num?,
      tongkhoiluong_tru_tapchat: json['tongkhoiluong_tru_tapchat'] as num?,
      sobao: json['sobao'] as num?,
      ngaycapstr: json['ngaycapstr'] as String?,
      tongkhoiluong: json['tongkhoiluong'] as num?,
      vctm_ghe: json['vctm_ghe'] == null
          ? null
          : VctmGheBean.fromJson(json['vctm_ghe'] as Map<String, dynamic>),
    )
      ..sophuongtien = json['sophuongtien'] as String?
      ..tenchughe = json['tenchughe'] as String?
      ..dienthoaichughe = json['dienthoaichughe'] as String?
      ..ngaycap = json['ngaycap'] as String?
      ..cmnd = json['cmnd'] as String?
      ..noicap = json['noicap'] as String?
      ..sanluongcan = json['sanluongcan'] as num?;

Map<String, dynamic> _$SoPhieuFilterModelToJson(SoPhieuFilterModel instance) =>
    <String, dynamic>{
      'sophieu': instance.sophieu,
      'id': instance.id,
      'idLocal': instance.idLocal,
      'sophieucan': instance.sophieucan,
      'idenct': instance.idenct,
      'so_bbtm': instance.so_bbtm,
      'mand': instance.mand,
      'tennd': instance.tennd,
      'makhuruong': instance.makhuruong,
      'tenkhuruong': instance.tenkhuruong,
      'magiong': instance.magiong,
      'tengiong': instance.tengiong,
      'ngaycan': instance.ngaycan,
      'ngaycanstr': instance.ngaycanstr,
      'ngaycoghe': instance.ngaycoghe,
      'ngaycoghestr': instance.ngaycoghestr,
      'tentinh': instance.tentinh,
      'tinh': instance.tinh,
      'tenhuyen': instance.tenhuyen,
      'huyen': instance.huyen,
      'tenxa': instance.tenxa,
      'xa': instance.xa,
      'ghichu': instance.ghichu,
      'tieuchuan': instance.tieuchuan,
      'sophuongtien': instance.sophuongtien,
      'tenchughe': instance.tenchughe,
      'dienthoaichughe': instance.dienthoaichughe,
      'ngaycap': instance.ngaycap,
      'ngaycapstr': instance.ngaycapstr,
      'cmnd': instance.cmnd,
      'noicap': instance.noicap,
      'giachot': instance.giachot,
      'dientichchot': instance.dientichchot,
      'tongkhoiluong_tru_tapchat': instance.tongkhoiluong_tru_tapchat,
      'tongkhoiluong_tru_bao': instance.tongkhoiluong_tru_bao,
      'sanluongcan': instance.sanluongcan,
      'tongkhoiluong': instance.tongkhoiluong,
      'sobao': instance.sobao,
      'vctm_ghe': instance.vctm_ghe,
      'canluaList': instance.canluaList,
      'isNotSync': instance.isNotSync,
    };

VctmGheBean _$VctmGheBeanFromJson(Map<String, dynamic> json) => VctmGheBean(
      mand: json['mand'] as String?,
      tennd: json['tennd'] as String?,
      makhuruong: json['makhuruong'] as String?,
      tenkhuruong: json['tenkhuruong'] as String?,
      macaytrong: json['macaytrong'] as String?,
      tencaytrong: json['tencaytrong'] as String?,
      magiong: json['magiong'] as String?,
      tengiong: json['tengiong'] as String?,
      tieuchuan: json['tieuchuan'] as String?,
      dientichchot: json['dientichchot'] as num?,
      bacung_can: json['bacung_can'] as bool?,
      sanluongdukien: json['sanluongdukien'] as num?,
      ngaythuhoachdk: json['ngaythuhoachdk'] as String?,
      ngaycatchot: json['ngaycatchot'] as String?,
      taitrongkenh: json['taitrongkenh'] as num?,
      maghe: json['maghe'] as String?,
      tenghe: json['tenghe'] as String?,
      sophuongtien: json['sophuongtien'] as String?,
      ngaylenghe: json['ngaylenghe'] as String?,
      ngayghevenhamay: json['ngayghevenhamay'] as String?,
      giachot: json['giachot'] as num?,
      giavanchuyen: json['giavanchuyen'] as num?,
      giabocxep: json['giabocxep'] as num?,
      luongvanchuyen: json['luongvanchuyen'] as num?,
      createdby: json['createdby'] as String?,
      createdon: json['createdon'] == null
          ? null
          : DateTime.parse(json['createdon'] as String),
      modifiedby: json['modifiedby'] as String?,
      modifiedon: json['modifiedon'] == null
          ? null
          : DateTime.parse(json['modifiedon'] as String),
      thuhoachdieughechitietidenct:
          json['thuhoachdieughechitietidenct'] as num?,
      trangthaivc: json['trangthaivc'] as num?,
      tentrangthaivc: json['tentrangthaivc'] as String?,
      trangthaivcon: json['trangthaivcon'] as String?,
      trangthaivcby: json['trangthaivcby'] as String?,
      thanhtien: json['thanhtien'] as num?,
      chkfile: json['chkfile'],
      madoighe: json['madoighe'] as String?,
      tendoighe: json['tendoighe'] as String?,
      tenchughe: json['tenchughe'] as String?,
      dienthoaichughe: json['dienthoaichughe'] as String?,
      cmnd: json['cmnd'] as String?,
      ngaycap: json['ngaycap'] as String?,
      noicap: json['noicap'] as String?,
      loaighe: json['loaighe'] as num?,
      gioghevenhamay: json['gioghevenhamay'] as String?,
      ngayhoanthanh: json['ngayhoanthanh'],
      giohoanthanh: json['giohoanthanh'],
      dongiathuong: json['dongiathuong'] as num?,
      denghiduyetgia: json['denghiduyetgia'] as String?,
      phulucso: json['phulucso'] as String?,
      tairuongby: json['tairuongby'] as String?,
      tairuongat: json['tairuongat'] as String?,
      dangvanchuyenby: json['dangvanchuyenby'],
      dangvanchuyenat: json['dangvanchuyenat'],
      tainhamayby: json['tainhamayby'],
      tainhamayat: json['tainhamayat'],
      hoanhthanhby: json['hoanhthanhby'],
      hoanhthanhat: json['hoanhthanhat'],
      ngayvenhamaybaocao: json['ngayvenhamaybaocao'] as String?,
      ngayhoanthanhbaocao: json['ngayhoanthanhbaocao'],
      vanchuyenve: json['vanchuyenve'] as String?,
      idct: json['idct'] as String?,
      idenct: json['idenct'] as num?,
      makenhbh: json['makenhbh'] as String?,
      tenkenhbh: json['tenkenhbh'] as String?,
      makhach: json['makhach'] as String?,
      tenkhach: json['tenkhach'] as String?,
      so_bbtm: json['so_bbtm'] as String?,
      sanluongcan: json['sanluongcan'] as num?,
      sobao: json['sobao'] as num?,
      khoiluong_bao: json['khoiluong_bao'] as num?,
      tongkhoiluong_tru_bao: json['tongkhoiluong_tru_bao'] as num?,
      khoiluong_tapchat: json['khoiluong_tapchat'] as num?,
      tongkhoiluong_tru_tapchat: json['tongkhoiluong_tru_tapchat'] as num?,
      tongkhoiluong: json['tongkhoiluong'] as num?,
      sophieu: json['sophieu'],
      ngaylenghestr: json['ngaylenghestr'],
      ngayghevenhamaystr: json['ngayghevenhamaystr'],
      ngaycatchotstr: json['ngaycatchotstr'],
      ngaythuhoachdkstr: json['ngaythuhoachdkstr'],
      ngaycapstr: json['ngaycapstr'],
      ngayhoanthanhstr: json['ngayhoanthanhstr'],
      vanchuyenvetten: json['vanchuyenvetten'],
    );

Map<String, dynamic> _$VctmGheBeanToJson(VctmGheBean instance) =>
    <String, dynamic>{
      'mand': instance.mand,
      'tennd': instance.tennd,
      'makhuruong': instance.makhuruong,
      'tenkhuruong': instance.tenkhuruong,
      'macaytrong': instance.macaytrong,
      'tencaytrong': instance.tencaytrong,
      'magiong': instance.magiong,
      'tengiong': instance.tengiong,
      'tieuchuan': instance.tieuchuan,
      'dientichchot': instance.dientichchot,
      'sanluongdukien': instance.sanluongdukien,
      'ngaythuhoachdk': instance.ngaythuhoachdk,
      'ngaycatchot': instance.ngaycatchot,
      'taitrongkenh': instance.taitrongkenh,
      'maghe': instance.maghe,
      'tenghe': instance.tenghe,
      'sophuongtien': instance.sophuongtien,
      'ngaylenghe': instance.ngaylenghe,
      'ngayghevenhamay': instance.ngayghevenhamay,
      'giachot': instance.giachot,
      'giavanchuyen': instance.giavanchuyen,
      'giabocxep': instance.giabocxep,
      'luongvanchuyen': instance.luongvanchuyen,
      'createdby': instance.createdby,
      'createdon': instance.createdon?.toIso8601String(),
      'modifiedby': instance.modifiedby,
      'modifiedon': instance.modifiedon?.toIso8601String(),
      'thuhoachdieughechitietidenct': instance.thuhoachdieughechitietidenct,
      'trangthaivc': instance.trangthaivc,
      'tentrangthaivc': instance.tentrangthaivc,
      'trangthaivcon': instance.trangthaivcon,
      'trangthaivcby': instance.trangthaivcby,
      'thanhtien': instance.thanhtien,
      'chkfile': instance.chkfile,
      'madoighe': instance.madoighe,
      'tendoighe': instance.tendoighe,
      'tenchughe': instance.tenchughe,
      'dienthoaichughe': instance.dienthoaichughe,
      'cmnd': instance.cmnd,
      'ngaycap': instance.ngaycap,
      'noicap': instance.noicap,
      'loaighe': instance.loaighe,
      'gioghevenhamay': instance.gioghevenhamay,
      'ngayhoanthanh': instance.ngayhoanthanh,
      'giohoanthanh': instance.giohoanthanh,
      'dongiathuong': instance.dongiathuong,
      'denghiduyetgia': instance.denghiduyetgia,
      'phulucso': instance.phulucso,
      'tairuongby': instance.tairuongby,
      'tairuongat': instance.tairuongat,
      'dangvanchuyenby': instance.dangvanchuyenby,
      'dangvanchuyenat': instance.dangvanchuyenat,
      'tainhamayby': instance.tainhamayby,
      'tainhamayat': instance.tainhamayat,
      'hoanhthanhby': instance.hoanhthanhby,
      'hoanhthanhat': instance.hoanhthanhat,
      'ngayvenhamaybaocao': instance.ngayvenhamaybaocao,
      'ngayhoanthanhbaocao': instance.ngayhoanthanhbaocao,
      'vanchuyenve': instance.vanchuyenve,
      'idct': instance.idct,
      'bacung_can': instance.bacung_can,
      'idenct': instance.idenct,
      'makenhbh': instance.makenhbh,
      'tenkenhbh': instance.tenkenhbh,
      'makhach': instance.makhach,
      'tenkhach': instance.tenkhach,
      'so_bbtm': instance.so_bbtm,
      'sanluongcan': instance.sanluongcan,
      'sobao': instance.sobao,
      'khoiluong_bao': instance.khoiluong_bao,
      'tongkhoiluong_tru_bao': instance.tongkhoiluong_tru_bao,
      'khoiluong_tapchat': instance.khoiluong_tapchat,
      'tongkhoiluong_tru_tapchat': instance.tongkhoiluong_tru_tapchat,
      'tongkhoiluong': instance.tongkhoiluong,
      'sophieu': instance.sophieu,
      'ngaylenghestr': instance.ngaylenghestr,
      'ngayghevenhamaystr': instance.ngayghevenhamaystr,
      'ngaycatchotstr': instance.ngaycatchotstr,
      'ngaythuhoachdkstr': instance.ngaythuhoachdkstr,
      'ngaycapstr': instance.ngaycapstr,
      'ngayhoanthanhstr': instance.ngayhoanthanhstr,
      'vanchuyenvetten': instance.vanchuyenvetten,
    };
